### ISSUE TITLE
week 07 - day 04 - welcome to jurassic park  - 

### ISSUE THREAD

**Issue by uncrownedthrone** [uncrownedthrone/assignments#31]
# Welcome to Jurassic Park

Today you learned a new language and will be starting to explore it more in depth in the coming weeks. Like any good craftsman, the first thing you need is to learn your tools. Tonight, you will be setting up your developer environment, creating a simple console application, and continuing your final project.

## Objectives

- Set up your dev machines
- Create a simple console application to ensure your machine is set up correctly
- keep working through your wireframes for your capstone

## Requirements

- Create a simple console application that manages the dinosaurs in your amusement park

#### .NET

- [x] Create a new console application that will store the list of dinosaurs they have in the park
- [x] You will be creating a class for your dinosaurs
- [x] a Dinosaur has the following properties

  - [x] Name
  - [x] DietType - This will be carnivore or herbivore
  - [x] DateAcquired - This will be defaulted when the dinosaur is created
  - [x] Weight - In pounds, how heavy the dinosaur is
  - [x] EnclosureNumber - the Pen that the dinosaur is currently on

- [x] Your dinosaurs will be stored in a `List<Dinosaur>`.
- [x] When the console application runs, it should let the user choose one of the following actions:
  - [x] View All the current dinosaurs
    - this command will show the all the dinosaurs in a the list, ordered by DateAcquired
  - [x] Add a new dinosaur
    - [x] This command will let the user type in the information for a dinosaur and add it to the list
  - [x] Remove a dinosaur
    - [x] This will delete a dinosaur by name
  - [x] Transfer
    - [x] Add the ability to update a dinosaur to a new enclosure
  - [x] View The 3 heaviest dinosaurs
  - [x] Diet summary
    - [x] This will the total number of each type of diet
  - [x] quit the program
    - [x] this will stop the program

#### Capstone

- [x] Work on your wire frames and ironing out your idea. Work with your instructors and peers to work out the kinks. Ideas should be approved by tomorrow.
- [x] If you idea is approved start coding.
- [x] Start thinking and mapping out your ERD for your database

### Adventure Mode

- [ ] Your data is currently stored in a list. This list is lost everytime the program restarts. [Add a database](https://suncoast.io/handbook/curriculum/back-end/full-stack-i/lecture/dotnet/04-entity-framework/)
- [ ] Eventually we will be using a MVC application structure. To prepare for this, refactor your code to have all your business logic in separate class and all your console interaction in the main class.

### Epic Mode

- [ ] On Monday, we will creating our first API. [Try it yourself](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)

## Additional Resources

- .NET

  - [.NET Documentation](https://docs.microsoft.com/en-us/dotnet/)
  - [Lecture Notes](https://suncoast.io/handbook/curriculum/back-end/full-stack-i/lecture/dotnet)

**Comment by uncrownedthrone** [comment]
https://github.com/uncrownedthrone/welcome-to-jurassic-park

**Comment by mdewey** [comment]
I loved the references! https://github.com/uncrownedthrone/welcome-to-jurassic-park/blob/master/Program.cs#L132
