### ISSUE TITLE
week 01 - day 03 - spooky portfolio  - responsive website

### ISSUE THREAD

**Issue by uncrownedthrone** [uncrownedthrone/assignments#9]
# A Spooky Portfolio

For your first weekend project, we're going to be starting work on a portfolio website that you can improve over the rest of your career.

[Recreate this Spooky Portfolio Mockup](https://github.com/suncoast-devs/handbook/blob/master/curriculum/fundamentals/modules/html-css/projects/mobile.png?raw=true)

> [You can find image assets you'll need here](https://github.com/suncoast-devs/handbook/tree/master/curriculum/fundamentals/modules/html-css/projects/assets)

The font used is [Josefun Sans](https://fonts.google.com/specimen/Josefin+Sans).

## Objectives

- Build on your knowledge of HTML & CSS
- Implement, from scratch, a given design
- Use flexbox techniques layout pages.

## Requirements

- Recreate this site as close as possible

- As discussed in class, it is easier to start with the mobile look first and then create the desktop. Follow the requirements in order for this assignment.

- Remember, start with HTML first and get the content going.

- You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [x] Recreate the [mobile UI](https://github.com/suncoast-devs/handbook/blob/master/curriculum/fundamentals/modules/html-css/projects/mobile.png?raw=true)
- [x] Update your site to be response for [tablets](https://github.com/suncoast-devs/handbook/blob/master/curriculum/fundamentals/modules/html-css/projects/tablet.png?raw=true)
- [x] Update your site to be responsive for [desktops](https://github.com/suncoast-devs/handbook/blob/master/curriculum/fundamentals/modules/html-css/projects/desktop.png?raw=true)
- [x] Deploy your site

### Adventure Mode

- [ ] Head over to [here](https://halloween-portfolio-markdewey.netlify.com/). There are animations and hover effects that are not in the mock ups. Implement those using only CSS.

### Epic Mode

- [ ] Take the time to personalize the site with information about yourself, links to your projects, and your pictures.
- [ ] Keep it professional, but make it your own.
- [ ] Start to research [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript)

**Comment by uncrownedthrone** [comment]
https://github.com/uncrownedthrone/spooky-portfolio

**Comment by mdewey** [comment]
Missing the desktop view, but still good work.
